apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: tema-std
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
              name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: tema-std
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30679
  selector:
    app: redis
