apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: tema-std
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
