apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: tema-std
  labels:
    app: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: vasileborcila/temastd:wordpress # Schimbă de la localhost:5000
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql-service
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
            - name: WORDPRESS_HOME
              value: "http://localhost"
          # volumeMounts:  # Comentat temporar!
          #   - name: wordpress-data
          #     mountPath: /var/www/html
      # volumes:  # Comentat temporar!
      #   - name: wordpress-data
      #     persistentVolumeClaim:
      #       claimName: wordpress-data
