apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: azure-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.0.0.100-10.0.0.200 # Interval IP-uri disponibile în rețeaua Azure
  autoAssign: true

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: azure-l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - azure-pool
  interfaces:
    - eth0 # Interfața de rețea a nodurilor
