apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-frontend
  namespace: tema-std
  labels:
    app: chat-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-frontend
  template:
    metadata:
      labels:
        app: chat-frontend
    spec:
      containers:
        - name: chat-frontend
          image: vasileborcila/temastd:chat-frontend
          ports:
            - containerPort: 90
