apiVersion: v1
kind: Service
metadata:
  name: chat-frontend-service
  namespace: tema-std
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.0.104
  labels:
    app: chat-frontend
spec:
  selector:
    app: chat-frontend
  ports:
    - port: 90
      targetPort: 90
      name: http
  type: LoadBalancer
  externalTrafficPolicy: Local
