apiVersion: v1
kind: Service
metadata:
  name: chat-backend-service
  namespace: tema-std
  labels:
    app: chat-backend
spec:
  selector:
    app: chat-backend
  ports:
    - port: 88
      targetPort: 88
      name: http
      nodePort: 30001
  type: NodePort
