apiVersion: v1
kind: Service
metadata:
  name: ai-frontend-service
  namespace: tema-std
  labels:
    app: ai-frontend
spec:
  selector:
    app: ai-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30426
  type: NodePort
