apiVersion: v1
kind: Service
metadata:
  name: ai-frontend-service
  namespace: tema-std
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.0.101
    # metallb.universe.tf/allow-shared-ip: shared-ip-key
  labels:
    app: ai-frontend
spec:
  selector:
    app: ai-frontend
  ports:
    - port: 100
      targetPort: 80
      name: http
  type: LoadBalancer
  externalTrafficPolicy: Local
